<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fr.paris.lutece.tools</groupId>
    <artifactId>lutece-global-pom</artifactId>
    <version>5.0.2</version>
  </parent>
  <groupId>fr.paris.lutece.plugins</groupId>
  <artifactId>plugin-fobienvu</artifactId>
  <version>1.0.7</version>
  <packaging>lutece-plugin</packaging>
  <name>Lutece fobienvu plugin</name>
  <url>https://github.com/plainecommune/espacepublic-plugin-fodansmarue</url>
  <scm>
    <connection>scm:git:https://github.com/plainecommune/espacepublic-plugin-fodansmarue.git</connection>
    <developerConnection>scm:git:https://github.com/plainecommune/espacepublic-plugin-fodansmarue.git</developerConnection>
    <url>https://github.com/plainecommune/espacepublic-plugin-fodansmarue</url>
    <tag>plugin-fobienvu-1.0.7</tag>
  </scm>
  <properties>
    <jiraComponentId />
    <profile.local.dir>${basedir}/src/conf/local</profile.local.dir>
    <profile.production.dir>${basedir}/src/conf/prod</profile.production.dir>
    <profile.dev.dir>${basedir}/src/conf/dev</profile.dev.dir>
    <jiraProjectName>FODANSMARUE</jiraProjectName>
    <profile.recette.dir>${basedir}/src/conf/rec</profile.recette.dir>
    <componentName>fodansmarue</componentName>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <profile.pre-recette.dir>${basedir}/src/conf/prerec</profile.pre-recette.dir>
    <maven.javadoc.skip>true</maven.javadoc.skip>
    <module.leaflet-bienvu.version>0.0.6-SNAPSHOT</module.leaflet-bienvu.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>fr.paris.lutece</groupId>
        <artifactId>lutece-core</artifactId>
        <version>6.1.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>fr.paris.lutece</groupId>
      <artifactId>lutece-core</artifactId>
      <version>6.1.0</version>
      <type>lutece-core</type>
    </dependency>
    <dependency>
      <groupId>fr.paris.lutece.plugins</groupId>
      <artifactId>plugin-unittree</artifactId>
      <version>2.1.2</version>
    </dependency>
    <dependency>
      <groupId>fr.paris.lutece.plugins</groupId>
      <artifactId>library-signrequest</artifactId>
      <version>3.0.0</version>
    </dependency>
    <dependency>
      <groupId>fr.paris.lutece.plugins</groupId>
      <artifactId>plugin-rest</artifactId>
      <version>3.1.0</version>
      <type>lutece-plugin</type>
    </dependency>
    <dependency>
      <groupId>fr.paris.lutece.plugins</groupId>
      <artifactId>module-leaflet-bienvu</artifactId>
      <version>${module.leaflet-bienvu.version}</version>
      <type>lutece-plugin</type>
    </dependency>
    <dependency>
      <groupId>fr.paris.lutece.plugins</groupId>
      <artifactId>plugin-leaflet</artifactId>
      <version>1.0.0</version>
      <type>lutece-plugin</type>
    </dependency>
    <dependency>
      <groupId>fr.paris.lutece.plugins</groupId>
      <artifactId>plugin-asynchronousupload</artifactId>
      <version>1.0.5</version>
      <type>lutece-plugin</type>
    </dependency>
	<dependency>
	    <groupId>org.postgresql</groupId>
	    <artifactId>postgresql</artifactId>
	    <version>42.2.23</version>
	</dependency>
    <dependency>
      <groupId>org.codehaus.jettison</groupId>
      <artifactId>jettison</artifactId>
      <version>1.1</version>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <releases />
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>luteceReleaseRepository</id>
      <name>luteceReleaseRepository</name>
      <url>https://dev.lutece.paris.fr/nexus/content/groups/maven_repository/</url>
    </repository>
    <repository>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots />
      <id>luteceSnapshotRepository</id>
      <name>luteceSnapshotRepository</name>
      <url>https://dev.lutece.paris.fr/nexus/content/groups/snapshot_repository/</url>
    </repository>
  </repositories>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-release-plugin</artifactId>
        <version>2.5.3</version>
        <configuration combine.self="override">
          <tagNameFormat>plugin-fobienvu-@{project.version}</tagNameFormat>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.5</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
